In [1]:
import numpy as np

In [2]:
#exo1

rng = np.random.default_rng(seed=12345)
X1 = rng.uniform(0,1,10)
X2 = rng.uniform(size=10)
X1, X2

(array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
        0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287]),
 array([0.24824571, 0.94888115, 0.66723745, 0.09589794, 0.44183967,
        0.88647992, 0.6974535 , 0.32647286, 0.73392816, 0.22013496]))

In [3]:
#exo2

x = np.arange(10)

x[[0, 3, 5]]
x[x%2 == 0]
x[1:]
x[:5]

array([0, 1, 2, 3, 4])

In [4]:
#exo3

x = rng.standard_normal(size=10000)

print(f"{len(x[np.abs(x) > 1.96])/len(x):0.2%}")
print(f"{np.sum(x[np.abs(x) > 1.96])/np.sum(x):0.2%}")




5.27%
-151.89%


In [5]:
#exo4

#assuming rng has been created beforhand

x = rng.normal(0, size=(3,4))
y = np.array([np.nan, 0, 1])

print(f"Count_nonzro y: {np.count_nonzero(y)}")
print(f"Isnan y: {np.isnan(y)}")

print(x)
np.any(x>0, axis=0)

Count_nonzro y: 2
Isnan y: [ True False False]
[[ 0.24679828  0.20259702 -2.16479669  1.78021858]
 [-0.95708055  1.44760026  1.15068019  1.29881139]
 [ 0.15163691 -0.84449914 -0.7795018   1.18436018]]


array([ True,  True,  True,  True])

In [6]:
#exo5

x = rng.normal(0, size=(3, 4))
print(x)

print(np.sum(x, axis=1))
print(np.sum(x, axis=0))
print(np.sum(x))

[[-0.49117853  0.36387465 -0.38447117 -0.58515095]
 [ 0.90562774 -0.93336641 -0.22161633 -0.30364229]
 [ 0.12007745 -0.12667196 -1.0262208  -0.42710596]]
[-1.09692601 -0.55299728 -1.45992126]
[ 0.53452666 -0.69616372 -1.63230829 -1.3158992 ]
-3.109844548963865


In [ ]:
#exo6

