In [4]:
import numpy as np

In [ ]:
#exo1

rng = np.random.default_rng(seed=12345)
X1 = rng.uniform(0,1,10)
X2 = rng.uniform(size=10)
X1, X2

(array([0.22733602, 0.31675834, 0.79736546, 0.67625467, 0.39110955,
        0.33281393, 0.59830875, 0.18673419, 0.67275604, 0.94180287]),
 array([0.24824571, 0.94888115, 0.66723745, 0.09589794, 0.44183967,
        0.88647992, 0.6974535 , 0.32647286, 0.73392816, 0.22013496]))

In [18]:
#exo2

x = np.arange(10)

x[[0, 3, 5]]
x[x%2 == 0]
x[1:]
x[:5]

array([0, 1, 2, 3, 4])

In [ ]:
#exo3

x = rng.standard_normal(size=10000)

print(f"{len(x[np.abs(x) > 1.96])/len(x):0.2%}")
print(f"{np.sum(x[np.abs(x) > 1.96])/np.sum(x):0.2%}")




4.97%
200.81%


In [ ]:
#exo4

#assuming rng has been created beforhand

x = rng.normal(0, size=(3,4))
y = np.array([np.nan, 0, 1])

print(f"Count_nonzro y: {np.count_nonzero(y)}")
print(f"Isnan y: {np.isnan(y)}")

print(x)
np.any(x>0, axis=0)

Count_nonzro y: 2
Isnan y: [ True False False]
[[-0.16755984 -0.84130562  0.10413851 -0.93523199]
 [ 0.00936821  1.0444189   1.15236599  0.12656809]
 [-1.80848028  1.2564038  -0.14153494 -1.80345655]]


array([ True,  True,  True,  True])

In [31]:
#exo5

x = rng.normal(0, size=(3, 4))
print(x)

print(np.sum(x, axis=1))
print(np.sum(x, axis=0))
print(np.sum(x))

[[ 0.3567917   0.62551691 -0.29024501  0.76474249]
 [-0.20381412 -0.67465706  1.23253    -0.52332696]
 [-2.25476646 -1.44144719  2.02209899 -0.51940949]]
[ 1.45680609 -0.16926815 -2.19352414]
[-2.10178888 -1.49058734  2.96438397 -0.27799396]
-0.9059862081553914
